#!/bin/bash
# Migrate ORION CDR archives from MinIO to Ceph
# Prerequisites:
#   - MinIO running with data
#   - Ceph RGW configured (run ceph-demo.sh first)
#   - AWS CLI or s3cmd installed

set -e

# Configuration
MINIO_ENDPOINT="http://localhost:9000"
MINIO_ACCESS_KEY="minioadmin"
MINIO_SECRET_KEY="minioadmin"
MINIO_BUCKET="orion-cdr-archive"

CEPH_ENDPOINT="http://localhost:7480"
CEPH_ACCESS_KEY="${CEPH_ACCESS_KEY:-$(docker exec ceph-mon1 radosgw-admin user info --uid=orion-storage-cold | grep -oP '\"access_key\": \"\K[^\"]+' | head -1)}"
CEPH_SECRET_KEY="${CEPH_SECRET_KEY:-$(docker exec ceph-mon1 radosgw-admin user info --uid=orion-storage-cold | grep -oP '\"secret_key\": \"\K[^\"]+' | head -1)}"
CEPH_BUCKET="orion-cdr-archive"

BACKUP_DIR="/tmp/orion-migration-$(date +%Y%m%d-%H%M%S)"

echo "🔄 ORION CDR Migration: MinIO → Ceph"
echo "====================================="
echo ""
echo "Source (MinIO):"
echo "  Endpoint: $MINIO_ENDPOINT"
echo "  Bucket: $MINIO_BUCKET"
echo ""
echo "Destination (Ceph):"
echo "  Endpoint: $CEPH_ENDPOINT"
echo "  Bucket: $CEPH_BUCKET"
echo ""
echo "Backup directory: $BACKUP_DIR"
echo ""

# Validate prerequisites
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Install with: pip install awscli"
    exit 1
fi

echo "✅ Prerequisites validated"
echo ""

# Step 1: Backup MinIO data
echo "1️⃣  Backing up MinIO data..."
mkdir -p "$BACKUP_DIR"

export AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY

OBJECT_COUNT=$(aws s3 ls s3://$MINIO_BUCKET --recursive \
    --endpoint-url $MINIO_ENDPOINT \
    --region us-east-1 2>/dev/null | wc -l)

echo "   Found $OBJECT_COUNT objects in MinIO"

if [ $OBJECT_COUNT -eq 0 ]; then
    echo "⚠️  No objects to migrate. Exiting."
    exit 0
fi

aws s3 sync s3://$MINIO_BUCKET "$BACKUP_DIR" \
    --endpoint-url $MINIO_ENDPOINT \
    --region us-east-1

echo "✅ Backup complete: $BACKUP_DIR"
echo ""

# Step 2: Verify Ceph RGW
echo "2️⃣  Verifying Ceph RGW..."

export AWS_ACCESS_KEY_ID=$CEPH_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$CEPH_SECRET_KEY

# Create bucket if not exists
aws s3 mb s3://$CEPH_BUCKET \
    --endpoint-url $CEPH_ENDPOINT \
    --region default 2>/dev/null || echo "   Bucket already exists"

echo "✅ Ceph RGW ready"
echo ""

# Step 3: Upload to Ceph
echo "3️⃣  Uploading to Ceph..."

aws s3 sync "$BACKUP_DIR" s3://$CEPH_BUCKET \
    --endpoint-url $CEPH_ENDPOINT \
    --region default

echo "✅ Upload complete"
echo ""

# Step 4: Verify migration
echo "4️⃣  Verifying migration..."

CEPH_OBJECT_COUNT=$(aws s3 ls s3://$CEPH_BUCKET --recursive \
    --endpoint-url $CEPH_ENDPOINT \
    --region default | wc -l)

echo "   MinIO objects: $OBJECT_COUNT"
echo "   Ceph objects: $CEPH_OBJECT_COUNT"

if [ $OBJECT_COUNT -eq $CEPH_OBJECT_COUNT ]; then
    echo "✅ Object counts match!"
else
    echo "⚠️  Object counts differ. Review logs."
    exit 1
fi
echo ""

# Step 5: Test read from Ceph
echo "5️⃣  Testing read from Ceph..."

SAMPLE_KEY=$(aws s3 ls s3://$CEPH_BUCKET --recursive \
    --endpoint-url $CEPH_ENDPOINT \
    --region default | head -1 | awk '{print $4}')

if [ -n "$SAMPLE_KEY" ]; then
    aws s3 cp s3://$CEPH_BUCKET/$SAMPLE_KEY /tmp/test-read.tmp \
        --endpoint-url $CEPH_ENDPOINT \
        --region default
    
    echo "✅ Read test successful (sample: $SAMPLE_KEY)"
    rm /tmp/test-read.tmp
else
    echo "⚠️  No objects found for read test"
fi
echo ""

# Step 6: Update ORION configuration
echo "6️⃣  Updating ORION configuration..."

cat > orion-storage-cold/.env.ceph <<EOF
# Ceph RGW Configuration (generated by migrate-minio-to-ceph.sh)
S3_ENDPOINT=$CEPH_ENDPOINT
S3_REGION=default
S3_BUCKET=$CEPH_BUCKET
S3_ACCESS_KEY=$CEPH_ACCESS_KEY
S3_SECRET_KEY=$CEPH_SECRET_KEY
S3_PATH_STYLE=true
EOF

echo "✅ Configuration written to orion-storage-cold/.env.ceph"
echo ""

# Step 7: Test ORION integration
echo "7️⃣  Testing ORION integration..."

if [ -f "orion-storage-cold/target/release/orion-storage-cold" ]; then
    echo "   Run orion-storage-cold with:"
    echo "   export \$(cat orion-storage-cold/.env.ceph | xargs)"
    echo "   ./orion-storage-cold/target/release/orion-storage-cold"
else
    echo "   Build orion-storage-cold first:"
    echo "   cd orion-storage-cold && cargo build --release"
fi
echo ""

echo "✅ Migration Complete!"
echo ""
echo "📋 Summary:"
echo "  - Backup directory: $BACKUP_DIR"
echo "  - Objects migrated: $OBJECT_COUNT"
echo "  - Ceph endpoint: $CEPH_ENDPOINT"
echo ""

echo "🚀 Next steps:"
echo "  1. Test orion-storage-cold with Ceph configuration"
echo "  2. Verify all CDR queries work correctly"
echo "  3. Monitor Ceph cluster: docker exec ceph-mon1 ceph -s"
echo "  4. Once validated, decommission MinIO"
echo ""

echo "⚠️  Rollback instructions:"
echo "  - Backup preserved at: $BACKUP_DIR"
echo "  - Revert to MinIO by changing S3_ENDPOINT back to $MINIO_ENDPOINT"
echo "  - Restore from backup: aws s3 sync $BACKUP_DIR s3://$MINIO_BUCKET --endpoint-url $MINIO_ENDPOINT"
